name: my-docker-project

services:
  django_app:
    build: .
    image: my-app-image
    container_name: my-app-container
    command: gunicorn DFA.wsgi:application --bind 0.0.0.0:8000

  nginx:
    image: nginx:latest
    command: rm /etc/nginx/conf.d/default.conf
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - django_app